services:

  # ─── AUTH ───────────────────────────────────────────
  auth-postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=authdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d authdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  auth-service:
    build:
      context: ../breezy-auth-service
      dockerfile: Dockerfile
    env_file:
      - ../breezy-auth-service/.env
    environment:
      - DB_HOST=auth-postgres
    depends_on:
      auth-postgres:
        condition: service_healthy
    networks:
      - app-network

  # ─── MONGO ───────────────────────────────────────────
  mongo:
    image: mongo:7
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ─── POST ────────────────────────────────────────────
  post-service:
    build:
      context: ../breezy-post-service
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://mongo:27017/breezy_posts
      - PORT=3002
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app-network

  # ─── USER ────────────────────────────────────────────
  user-service:
    build:
      context: ../breezy-user-service
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://mongo:27017/breezy_users
      - PORT=3001
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app-network

  # ─── FRONT ───────────────────────────────────────────
  front:
    build:
      context: ../breezy-front
      dockerfile: Dockerfile
    networks:
      - app-network

  # ─── GATEWAY ─────────────────────────────────────────
  nginx:
    image: nginx:alpine
    container_name: gateway
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - auth-service
      - post-service
      - user-service
      - front
    networks:
      - app-network

volumes:
  auth-db-data:
  mongo-data:

networks:
  app-network:
    driver: bridge